#!/bin/bash
rm glparchis-*.tar.gz
DIR=glparchis-`cat libglparchis.py | grep 'version="2'| cut --delimiter='"'  -f 2`
FILE=$DIR.tar.gz
echo "Este script crea el fichero $FILE para ser subido a sourceforge"

mkdir $DIR
mkdir $DIR/doc
mkdir $DIR/i18n
mkdir $DIR/images
mkdir $DIR/ui
mkdir $DIR/saves
mkdir $DIR/sounds

cp      Makefile \
	AUTHORS-ES.txt \
	AUTHORS-EN.txt \
        CHANGELOG-EN.txt \
        CHANGELOG-ES.txt \
        GPL-3.txt \
        INSTALL-EN.txt \
        INSTALL-ES.txt \
        RELEASES-EN.txt \
        RELEASES-ES.txt \
        glparchis.py \
        glparchis.pro \
        libglparchis.py \
        glparchis.desktop \
        $DIR

cp      i18n/*.ts \
        $DIR/i18n

cp 	doc/*.odt \
	doc/*.odg \
        $DIR/doc

cp 	ui/frm* \
	ui/wdg* \
	ui/q* \
	$DIR/ui

cp	images/*.png \
	images/*.qrc \
	$DIR/images

cp 	sounds/*.ogg \
	$DIR/sounds

cp 	saves/*.glparchis \
	$DIR/saves

tar cvz $DIR -f $FILE
rm -R $DIR
chmod 666 $FILE
