#!/bin/bash
rm myquotes-*.tar.gz
DIR=myquotes-`cat ./myquotesd.py | grep 'version="2'| cut --delimiter='"'  -f 2`
FILE=$DIR.tar.gz
echo "Este script crea el fichero $FILE para ser subido a sourceforge"

mkdir $DIR
mkdir $DIR/doc
mkdir $DIR/sql
mkdir $DIR/myquotes
mkdir $DIR/myquotes/ui
mkdir $DIR/myquotes/i18n
mkdir $DIR/myquotes/images

cp      Makefile \
	AUTHORS-ES.txt \
	AUTHORS-EN.txt \
        CHANGELOG-EN.txt \
        CHANGELOG-ES.txt \
        GPL-3.txt \
        INSTALL-EN.txt \
        INSTALL-ES.txt \
        RELEASES-EN.txt \
        RELEASES-ES.txt \
        myquotes.initd \
        myquotesd.py \
        libmyquotes.py \
        config.py \
        myquotes-myquotes.desktop \
        $DIR

cp      po/en.po \
        po/myquotes.pot \
        po/translate \
        $DIR/po

cp 	doc/*.odt \
        $DIR/doc

cp 	sql/myquotes.* \
	$DIR/sql

cp	myquotes/myquotes* \
        $DIR/myquotes

cp 	myquotes/i18n/*.ts \
	$DIR/myquotes/i18n

cp	myquotes/ui/frm* \
	myquotes/ui/wdg* \
	$DIR/myquotes/ui

cp	myquotes/images/*.png \
	myquotes/images/*.gif \
	myquotes/images/*.jpg \
	myquotes/images/*.qrc \
	$DIR/myquotes/images

tar cvz $DIR -f $FILE
rm -R $DIR
chmod 666 $FILE
