# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/keko/Proyectos/glparchis/pyglParchis/ui/frmMain.ui'
#
# Created: Fri May 21 16:50:33 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName("frmMain")
        frmMain.resize(877, 596)
        frmMain.setCursor(QtCore.Qt.PointingHandCursor)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/glparchis/ficharoja.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmMain.setWindowIcon(icon)
        self.wdg = QtGui.QWidget(frmMain)
        self.wdg.setObjectName("wdg")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.wdg)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.panel1 = QtGui.QWidget(self.wdg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panel1.sizePolicy().hasHeightForWidth())
        self.panel1.setSizePolicy(sizePolicy)
        self.panel1.setMinimumSize(QtCore.QSize(378, 125))
        self.panel1.setObjectName("panel1")
        self.verticalLayout.addWidget(self.panel1)
        self.panel2 = QtGui.QWidget(self.wdg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panel2.sizePolicy().hasHeightForWidth())
        self.panel2.setSizePolicy(sizePolicy)
        self.panel2.setMinimumSize(QtCore.QSize(378, 125))
        self.panel2.setObjectName("panel2")
        self.verticalLayout.addWidget(self.panel2)
        self.panel3 = QtGui.QWidget(self.wdg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panel3.sizePolicy().hasHeightForWidth())
        self.panel3.setSizePolicy(sizePolicy)
        self.panel3.setMinimumSize(QtCore.QSize(378, 125))
        self.panel3.setObjectName("panel3")
        self.verticalLayout.addWidget(self.panel3)
        self.panel4 = QtGui.QWidget(self.wdg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panel4.sizePolicy().hasHeightForWidth())
        self.panel4.setSizePolicy(sizePolicy)
        self.panel4.setMinimumSize(QtCore.QSize(378, 125))
        self.panel4.setObjectName("panel4")
        self.verticalLayout.addWidget(self.panel4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tab = QtGui.QTabWidget(self.wdg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setAutoFillBackground(True)
        self.tab.setTabShape(QtGui.QTabWidget.Rounded)
        self.tab.setElideMode(QtCore.Qt.ElideMiddle)
        self.tab.setObjectName("tab")
        self.tabGame = QtGui.QWidget()
        self.tabGame.setObjectName("tabGame")
        self.hboxlayout = QtGui.QHBoxLayout(self.tabGame)
        self.hboxlayout.setObjectName("hboxlayout")
        self.ogl = wdgOpenGL(self.tabGame)
        self.ogl.setSizeIncrement(QtCore.QSize(10, 10))
        self.ogl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.ogl.setObjectName("ogl")
        self.hboxlayout.addWidget(self.ogl)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/glparchis/keko.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tab.addTab(self.tabGame, icon1, "")
        self.tabStatistics = QtGui.QWidget()
        self.tabStatistics.setObjectName("tabStatistics")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.tabStatistics)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.lst = QtGui.QTreeView(self.tabStatistics)
        self.lst.setObjectName("lst")
        self.hboxlayout1.addWidget(self.lst)
        self.tab.addTab(self.tabStatistics, "")
        self.horizontalLayout.addWidget(self.tab)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        frmMain.setCentralWidget(self.wdg)
        self.menuBar = QtGui.QMenuBar(frmMain)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 877, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuAyuda = QtGui.QMenu(self.menuBar)
        self.menuAyuda.setObjectName("menuAyuda")
        self.menuJugar = QtGui.QMenu(self.menuBar)
        self.menuJugar.setObjectName("menuJugar")
        self.menuPreferencias = QtGui.QMenu(self.menuBar)
        self.menuPreferencias.setObjectName("menuPreferencias")
        frmMain.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(frmMain)
        self.toolBar.setObjectName("toolBar")
        frmMain.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.status = QtGui.QStatusBar(frmMain)
        self.status.setObjectName("status")
        frmMain.setStatusBar(self.status)
        self.actionSalir = QtGui.QAction(frmMain)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/glparchis/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSalir.setIcon(icon2)
        self.actionSalir.setObjectName("actionSalir")
        self.actionAcercaDe = QtGui.QAction(frmMain)
        self.actionAcercaDe.setIcon(icon)
        self.actionAcercaDe.setObjectName("actionAcercaDe")
        self.actionJugar = QtGui.QAction(frmMain)
        self.actionJugar.setIcon(icon1)
        self.actionJugar.setObjectName("actionJugar")
        self.actionLenguaje = QtGui.QAction(frmMain)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/glparchis/kbabel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLenguaje.setIcon(icon3)
        self.actionLenguaje.setObjectName("actionLenguaje")
        self.menuAyuda.addAction(self.actionAcercaDe)
        self.menuJugar.addAction(self.actionJugar)
        self.menuJugar.addSeparator()
        self.menuJugar.addAction(self.actionSalir)
        self.menuPreferencias.addAction(self.actionLenguaje)
        self.menuBar.addAction(self.menuJugar.menuAction())
        self.menuBar.addAction(self.menuPreferencias.menuAction())
        self.menuBar.addAction(self.menuAyuda.menuAction())
        self.toolBar.addAction(self.actionJugar)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLenguaje)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSalir)

        self.retranslateUi(frmMain)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        frmMain.setWindowTitle(QtGui.QApplication.translate("frmMain", "glParchis 2010", None, QtGui.QApplication.UnicodeUTF8))
        self.tab.setTabText(self.tab.indexOf(self.tabGame), QtGui.QApplication.translate("frmMain", "Juego", None, QtGui.QApplication.UnicodeUTF8))
        self.tab.setTabText(self.tab.indexOf(self.tabStatistics), QtGui.QApplication.translate("frmMain", "Estadísticas", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAyuda.setTitle(QtGui.QApplication.translate("frmMain", "A&yuda", None, QtGui.QApplication.UnicodeUTF8))
        self.menuJugar.setTitle(QtGui.QApplication.translate("frmMain", "J&ugar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPreferencias.setTitle(QtGui.QApplication.translate("frmMain", "P&referencias", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("frmMain", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalir.setText(QtGui.QApplication.translate("frmMain", "S&alir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAcercaDe.setText(QtGui.QApplication.translate("frmMain", "Acerca de", None, QtGui.QApplication.UnicodeUTF8))
        self.actionJugar.setText(QtGui.QApplication.translate("frmMain", "Jugar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLenguaje.setText(QtGui.QApplication.translate("frmMain", "I&dioma", None, QtGui.QApplication.UnicodeUTF8))

from wdgOpenGL import wdgOpenGL
import glparchis_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    frmMain = QtGui.QMainWindow()
    ui = Ui_frmMain()
    ui.setupUi(frmMain)
    frmMain.show()
    sys.exit(app.exec_())

