# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/keko/pyglParchis/ui/frmMain.ui'
#
# Created: Sun Jul 13 23:18:22 2008
#      by: PyQt4 UI code generator 4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName("frmMain")
        frmMain.resize(QtCore.QSize(QtCore.QRect(0,0,718,632).size()).expandedTo(frmMain.minimumSizeHint()))
        frmMain.setCursor(QtCore.Qt.PointingHandCursor)
        frmMain.setWindowIcon(QtGui.QIcon(":/glparchis/ficharoja.png"))
        self.wdg = QtGui.QWidget(frmMain)
        self.wdg.setObjectName("wdg")
        self.vboxlayout = QtGui.QVBoxLayout(self.wdg)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.panel1 = QtGui.QWidget(self.wdg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panel1.sizePolicy().hasHeightForWidth())
        self.panel1.setSizePolicy(sizePolicy)
        self.panel1.setMinimumSize(QtCore.QSize(378,125))
        self.panel1.setObjectName("panel1")
        self.vboxlayout1.addWidget(self.panel1)
        self.panel2 = QtGui.QWidget(self.wdg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panel2.sizePolicy().hasHeightForWidth())
        self.panel2.setSizePolicy(sizePolicy)
        self.panel2.setMinimumSize(QtCore.QSize(378,125))
        self.panel2.setObjectName("panel2")
        self.vboxlayout1.addWidget(self.panel2)
        self.panel3 = QtGui.QWidget(self.wdg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panel3.sizePolicy().hasHeightForWidth())
        self.panel3.setSizePolicy(sizePolicy)
        self.panel3.setMinimumSize(QtCore.QSize(378,125))
        self.panel3.setObjectName("panel3")
        self.vboxlayout1.addWidget(self.panel3)
        self.panel4 = QtGui.QWidget(self.wdg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panel4.sizePolicy().hasHeightForWidth())
        self.panel4.setSizePolicy(sizePolicy)
        self.panel4.setMinimumSize(QtCore.QSize(378,125))
        self.panel4.setObjectName("panel4")
        self.vboxlayout1.addWidget(self.panel4)
        self.hboxlayout.addLayout(self.vboxlayout1)
        self.tab = QtGui.QTabWidget(self.wdg)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setAutoFillBackground(True)
        self.tab.setTabShape(QtGui.QTabWidget.Rounded)
        self.tab.setElideMode(QtCore.Qt.ElideMiddle)
        self.tab.setObjectName("tab")
        self.tabGame = QtGui.QWidget()
        self.tabGame.setObjectName("tabGame")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.tabGame)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.ogl = wdgOpenGL(self.tabGame)
        self.ogl.setObjectName("ogl")
        self.hboxlayout1.addWidget(self.ogl)
        self.tab.addTab(self.tabGame,QtGui.QIcon(":/glparchis/keko.png"),"")
        self.tabStatistics = QtGui.QWidget()
        self.tabStatistics.setObjectName("tabStatistics")
        self.hboxlayout2 = QtGui.QHBoxLayout(self.tabStatistics)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.lst = QtGui.QTreeView(self.tabStatistics)
        self.lst.setObjectName("lst")
        self.hboxlayout2.addWidget(self.lst)
        self.tab.addTab(self.tabStatistics,"")
        self.hboxlayout.addWidget(self.tab)
        self.vboxlayout.addLayout(self.hboxlayout)
        frmMain.setCentralWidget(self.wdg)
        self.menuBar = QtGui.QMenuBar(frmMain)
        self.menuBar.setGeometry(QtCore.QRect(0,0,718,30))
        self.menuBar.setObjectName("menuBar")
        self.menuAyuda = QtGui.QMenu(self.menuBar)
        self.menuAyuda.setObjectName("menuAyuda")
        self.menuJugar = QtGui.QMenu(self.menuBar)
        self.menuJugar.setObjectName("menuJugar")
        self.menuPreferencias = QtGui.QMenu(self.menuBar)
        self.menuPreferencias.setObjectName("menuPreferencias")
        frmMain.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(frmMain)
        self.toolBar.setObjectName("toolBar")
        frmMain.addToolBar(QtCore.Qt.TopToolBarArea,self.toolBar)
        self.status = QtGui.QStatusBar(frmMain)
        self.status.setObjectName("status")
        frmMain.setStatusBar(self.status)
        self.actionSalir = QtGui.QAction(frmMain)
        self.actionSalir.setIcon(QtGui.QIcon(":/glparchis/exit.png"))
        self.actionSalir.setObjectName("actionSalir")
        self.actionAcercaDe = QtGui.QAction(frmMain)
        self.actionAcercaDe.setIcon(QtGui.QIcon(":/glparchis/ficharoja.png"))
        self.actionAcercaDe.setObjectName("actionAcercaDe")
        self.actionJugar = QtGui.QAction(frmMain)
        self.actionJugar.setIcon(QtGui.QIcon(":/glparchis/keko.png"))
        self.actionJugar.setObjectName("actionJugar")
        self.actionLenguaje = QtGui.QAction(frmMain)
        self.actionLenguaje.setIcon(QtGui.QIcon(":/glparchis/kbabel.png"))
        self.actionLenguaje.setObjectName("actionLenguaje")
        self.menuAyuda.addAction(self.actionAcercaDe)
        self.menuJugar.addAction(self.actionJugar)
        self.menuJugar.addSeparator()
        self.menuJugar.addAction(self.actionSalir)
        self.menuPreferencias.addAction(self.actionLenguaje)
        self.menuBar.addAction(self.menuJugar.menuAction())
        self.menuBar.addAction(self.menuPreferencias.menuAction())
        self.menuBar.addAction(self.menuAyuda.menuAction())
        self.toolBar.addAction(self.actionJugar)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLenguaje)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSalir)

        self.retranslateUi(frmMain)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        frmMain.setWindowTitle(QtGui.QApplication.translate("frmMain", "glParchis 2008", None, QtGui.QApplication.UnicodeUTF8))
        self.tab.setTabText(self.tab.indexOf(self.tabGame), QtGui.QApplication.translate("frmMain", "Juego", None, QtGui.QApplication.UnicodeUTF8))
        self.tab.setTabText(self.tab.indexOf(self.tabStatistics), QtGui.QApplication.translate("frmMain", "Estadísticas", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAyuda.setTitle(QtGui.QApplication.translate("frmMain", "A&yuda", None, QtGui.QApplication.UnicodeUTF8))
        self.menuJugar.setTitle(QtGui.QApplication.translate("frmMain", "J&ugar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPreferencias.setTitle(QtGui.QApplication.translate("frmMain", "P&referencias", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("frmMain", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalir.setText(QtGui.QApplication.translate("frmMain", "S&alir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAcercaDe.setText(QtGui.QApplication.translate("frmMain", "Acerca de", None, QtGui.QApplication.UnicodeUTF8))
        self.actionJugar.setText(QtGui.QApplication.translate("frmMain", "Jugar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLenguaje.setText(QtGui.QApplication.translate("frmMain", "I&dioma", None, QtGui.QApplication.UnicodeUTF8))

from wdgOpenGL import wdgOpenGL
import glparchis_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    frmMain = QtGui.QMainWindow()
    ui = Ui_frmMain()
    ui.setupUi(frmMain)
    frmMain.show()
    sys.exit(app.exec_())

